### ISSUE TITLE
Blazon textfield disappears immediately on Firefox

### ISSUE THREAD

**Issue by mount2010** [karlwilcox/Drawshield-Code#9]
On Firefox 70 on Linux, the Blazon entry field on the Create page immediately disappears when the page loads. 

The console says:
ReferenceError: SocialShareKit is not defined

**Comment by karlwilcox** [comment]
Sorry, I can't reproduce this, tried a couple of Linux variants. I use Ubuntu 18.04 and latest Firefox as my development environment so I usually spot these problems quite quickly. What happens when you do a complete page refresh? 
Having said that, the Social Share Kit is an external dependency that we don't really need, and everyone knows how to share by now, right?! I'll think about removing altogether anyway...

**Comment by mount2010** [comment]
Disabling Ublock Origin, Privacy Badger and HTTPS Everywhere removed all but one error, and disabling Content Blocking removed all the errors, but the field still disappears. Strange...

You might want to try with Ublock Origin, Privacy Badger, and HTTPS Everywhere... Given these plugins are quite essential for bare privacy on the Internet these days, it's quite important that your site works with them.

**Comment by mount2010** [comment]
![image](https://user-images.githubusercontent.com/13136505/69828102-6c7ef080-1255-11ea-8206-b1135ede503b.png)
Here's an image of what I see:

**Comment by mount2010** [comment]
For some weird reason, the field is set to display: none... I have no idea why, since all my plugins are off.

**Comment by karlwilcox** [comment]
Thanks for checking. I think I'll just take the Social sharing links out, they are not really needed and just create a dependency - I can then do some button rearranging to give a more logical "flow". Might find time later tonight...

**Comment by karlwilcox** [comment]
I have addressed this a couple of ways - the social share links have been removed completely as I don't think they are necessary anymore. The CodeMirror code has been updated to the latest version and I've added an option under preferences to turn the editor off and just use a textarea. Hence I think this one is now closed.

**Comment by mount2010** [comment]
Strange, the Fancy editor doesn't appear, still. Could this potentially be a CSS/JS issue? It's a shame that even a modern browser such as Firefox can't use the proper editor, as it was meant to...

I'm not getting any errors, but I still see display: none on the editor. Could it be that you are changing it to display: none somewhere and forgetting to change it back after the page loads, for some reason?

**Comment by mount2010** [comment]
Same problem occurs when I use a clean install of Firefox with no installed plugins and default settings. However, Opera works just fine. It kind of convinces me it's a Webkit/Gecko thing, for some reason?

**Comment by karlwilcox** [comment]
I don't have much to do with editor code, it is just a recent version of CodeMirror from https://codemirror.net/ . The code that invokes is actually in a separate repository here https://github.com/karlwilcox/drawshield-website/blob/master/source/_includes/blazon-editor.html  (lines 176 to 184 are they key ones). Unfortunately, unless I can replicate the problem I can't do much. Can you use the Firefox developer tools to see where the display: none comes from?

**Comment by mount2010** [comment]
I fired up a Ubuntu 18.04 LTS VM, and tried looking at the page. Strangely enough, on Firefox 68, the field doesn't disappear. However, on Firefox 70, it does. I wonder what broke? Do you have any browser-specific configuration somewhere?

**Comment by karlwilcox** [comment]
I think there is good news - I was able to reproduce this and tracked the problem down to a codemirror plugin (buttons panel) that had not been updated for a long time. I have removed this plug-in and replaced its functionality with native code and the problem no longer appears on my Linux testing. Please let me know if it is still a problem elsewhere.
